// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package in.mused.api.domain;

import in.mused.api.domain.Library;
import in.mused.api.domain.LibraryDataOnDemand;
import in.mused.api.service.LibraryService;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.bson.types.ObjectId;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect LibraryDataOnDemand_Roo_DataOnDemand {
    
    declare @type: LibraryDataOnDemand: @Component;
    
    private Random LibraryDataOnDemand.rnd = new SecureRandom();
    
    private List<Library> LibraryDataOnDemand.data;
    
    @Autowired
    LibraryService LibraryDataOnDemand.libraryService;
    
    public Library LibraryDataOnDemand.getNewTransientLibrary(int index) {
        Library obj = new Library();
        return obj;
    }
    
    public Library LibraryDataOnDemand.getSpecificLibrary(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Library obj = data.get(index);
        ObjectId id = obj.getId();
        return libraryService.findLibrary(id);
    }
    
    public Library LibraryDataOnDemand.getRandomLibrary() {
        init();
        Library obj = data.get(rnd.nextInt(data.size()));
        ObjectId id = obj.getId();
        return libraryService.findLibrary(id);
    }
    
    public boolean LibraryDataOnDemand.modifyLibrary(Library obj) {
        return false;
    }
    
    public void LibraryDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = libraryService.findLibraryEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Library' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Library>();
        for (int i = 0; i < 10; i++) {
            Library obj = getNewTransientLibrary(i);
            try {
                libraryService.saveLibrary(obj);
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            data.add(obj);
        }
    }
    
}
