// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package in.mused.api.domain;

import in.mused.api.domain.PlaylistIntegrationTest;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect PlaylistIntegrationTest_Roo_Configurable {
    
    declare @type: PlaylistIntegrationTest: @Configurable;
    
}
