// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package in.mused.api.domain;

import in.mused.api.domain.Playlist;
import in.mused.api.domain.PlaylistDataOnDemand;
import in.mused.api.service.PlaylistService;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.bson.types.ObjectId;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect PlaylistDataOnDemand_Roo_DataOnDemand {
    
    declare @type: PlaylistDataOnDemand: @Component;
    
    private Random PlaylistDataOnDemand.rnd = new SecureRandom();
    
    private List<Playlist> PlaylistDataOnDemand.data;
    
    @Autowired
    PlaylistService PlaylistDataOnDemand.playlistService;
    
    public Playlist PlaylistDataOnDemand.getNewTransientPlaylist(int index) {
        Playlist obj = new Playlist();
        return obj;
    }
    
    public Playlist PlaylistDataOnDemand.getSpecificPlaylist(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Playlist obj = data.get(index);
        ObjectId id = obj.getId();
        return playlistService.findPlaylist(id);
    }
    
    public Playlist PlaylistDataOnDemand.getRandomPlaylist() {
        init();
        Playlist obj = data.get(rnd.nextInt(data.size()));
        ObjectId id = obj.getId();
        return playlistService.findPlaylist(id);
    }
    
    public boolean PlaylistDataOnDemand.modifyPlaylist(Playlist obj) {
        return false;
    }
    
    public void PlaylistDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = playlistService.findPlaylistEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Playlist' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Playlist>();
        for (int i = 0; i < 10; i++) {
            Playlist obj = getNewTransientPlaylist(i);
            try {
                playlistService.savePlaylist(obj);
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            data.add(obj);
        }
    }
    
}
